connector.name=hive
hive.metastore=file
hive.metastore.catalog.dir=s3a://iceberg-data/
hive.s3.endpoint=http://minio:9000
hive.s3.path-style-access=true
hive.s3.aws-access-key=${TRINO_MINIO_ACCESS_KEY}
hive.s3.aws-secret-key=${TRINO_MINIO_SECRET_KEY}
hive.security=allow-all